language: java

jdk:
  - oraclejdk11

before_script:
  - chmod +x gradlew

script:
  - ./gradlew check
  - ./gradlew codeCoverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)

env:
  global:
    - CODECOV_TOKEN=2b10488b-f06d-491a-9d13-dba3e984708c